name: py35
dependencies:
- pytest=3.0.4=py35_0
- flake8=2.5.1=py35_0
- pip=9.0.1=py35_0
- python=3.5.1=0
- numpy=1.11.2=py35_0
- scipy=0.18.1=np111py35_0
- toolz=0.8.0=py35_0
- multipledispatch=0.4.9=py35_0
- pip:
  - custom_inherit
  - tableprint
