cache: apt
sudo: false
language: python
python:
  - "3.5"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda install pip numpy scipy
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py install
script:
  - pytest --cov=descent --cov-report=html tests/
after_success:
  - coveralls
