cache: apt
sudo: false
language: python
python:
  - "3.5"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes pip numpy
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py install
script:
  - pytest --cov=descent --cov-report=html tests/
after_success:
  - coveralls
